---
title: "🎤 Presentations"
site: distill::distill_website
output:
  distill::distill_article:
    css: presentations.css
---

<ul class="presentation-list">
  <li>
    <strong>Velayudhan, A.</strong> (2024, August 21–22). 
    <em>Variability in formant dynamics of long and short vowels in Malayalam</em>. 
    [Conference presentation]. International Seminar on AI and Large Language Models for Dravidian Languages, Department of Linguistics, Central University of Kerala, India.
  </li>

  <li>
    <strong>Velayudhan, A.</strong> (2022, January 12–14). 
    <em>A linguistic approach to the economic solidarity: The study on unorganised micro-enterprisers in Kerala tourism sector</em>. 
    [Conference presentation]. Web Conference on Cooperatives, Mutual Aid and Solidarity Economies, Department of Economics, University of Kerala, Thiruvananthapuram.
  </li>

  <li>
    <strong>Velayudhan, A.</strong> (2022, August 11–13). 
    <em>Lexemes of COVID-19: A linguistics study based on newspapers in Kerala</em>. 
    [Conference presentation]. Three-day National Webinar on Current Trends in Literature and Linguistics, School of Indian Languages, ONV Memorial Academic Complex, University of Kerala.
  </li>

  <li>
    <strong>Velayudhan, A.</strong> (2021, March 14–18). 
    <em>A dive into the impacts of ‘The First Bell’ among tribal students</em>. 
    [Conference presentation]. Five-day National Webinar on COVID-19: Vulnerability, Adaptation and Capacity Building among Tribal Communities, Department of Sociology, University of Kerala & IIST, Thiruvananthapuram.
  </li>

  <li>
    <strong>Velayudhan, A.</strong> (2019, December 10–12). 
    <em>Stylistic analysis of Slangyalam; Modern trends and propagations</em>. 
    [Conference presentation]. Three-day National Seminar on Current Trends in Language and Literature in India, School of Indian Languages, ONV Memorial Academic Complex, University of Kerala.
  </li>
</ul>
